# Generated by Django 3.2.7 on 2021-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromName', models.CharField(max_length=20)),
                ('fromDesignation', models.CharField(max_length=20)),
                ('toName', models.CharField(max_length=20)),
                ('toDesignation', models.CharField(max_length=20)),
                ('inChargeName', models.CharField(max_length=20)),
                ('inChargeDesignation', models.CharField(max_length=20)),
                ('teamLeadName', models.CharField(max_length=20)),
                ('teamLeadDesignation', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=20)),
                ('employeeDesignation', models.CharField(max_length=20)),
                ('employeeResponsibilities', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Engineers Details',
            },
        ),
    ]
